#config_version=5

mode:
  start_events: award_3_selected
  stop_events: award_3_unselected

shows:
  scratch_guards_activated:
    - duration: 3.5
      segment_displays:
        row_0:
          color: white
          text: " SCRATCH GUARDS "
          transition:
            type: push
            direction: left
        row_1:
          color: white
          text: "     ONLINE     "
          transition:
            type: push
            direction: right

event_player:
  award_3_collected: scratch_guards_start

# TODO: end this mode once the show is done playing
# TODO: add test so that show won't play twice if scratch guards are already activated
show_player:
  saucer_collect_award:
    scratch_guards_activated:
      loops: 0
      speed: 1.5
      priority: 100
      events_when_completed: award_x_show_complete
