#config_version=5

mode:
  start_events: ball_starting

shot_profiles:
  spot:
    states:
      - name: flash
        show: flash
        speed: 10

shots:
  sh_spot:
    switch: s_standup_center
    profile: spot
    show_tokens:
      light: l_standup_center

sound_player:
  sh_spot_hit: rack_advance

