#config_version=5

mode:
  start_events: ball_starting

show_player:
  ball_save_default_timer_start:
    flash_color:
      speed: 3
      show_tokens:
        light: l_ball_save
        color: white
  ball_save_default_hurry_up:
    flash_color:
      speed: 6
      show_tokens:
        light: l_ball_save
        color: white
  ball_save_default_disabled:
    flash_color:
      action: stop
    
  
