#config_version=5

mode:
  start_events: ball_starting

show_player:
  ball_save_default_timer_start:
    flash_color:
      speed: 5
      show_tokens:
        light: l_ball_save
        color: white
  ball_save_default_hurry_up:
    flash_color:
      speed: 10
      show_tokens:
        light: l_ball_save
        color: white
  ball_save_default_disabled:
    flash_color:
      action: stop
    
  
