#config_version=5

mode:
  start_events: award_1_selected
  stop_events: award_1_unselected


# TODO: end this mode once the show is done playing
# TODO: add test so that show won't play twice if scratch guards are already activate
show_player:
  saucer_collect_award_show_start:
    instant_million:
      loops: 0
      speed: 1
      priority: 100
      events_when_completed: award_x_show_complete

variable_player:
  saucer_collect_award_show_start:
    score: 1000000

event_player:
  awards_award_collected:
    announce_message:
      message: "instant million"
