#config_version=5

mode:
  start_events: ball_starting

# TODO: end this mode once the show is done playing
# TODO: add test so that show won't play twice if scratch guards are already activate
show_player:
  award_0_collected:
    instant_million:
      loops: 0
      speed: 1
      priority: 100


variable_player:
  award_0_collected:
    score: 1000000
