#config_version=5

slide_player:
  mode_attract_started.1:
    combined:
      target: window
  mode_attract_started.2:
    segment:
      target: normal
  mode_attract_started.3:
    background:
      target: background

shows:
  attract_segment:
    - time: 0
      segment_displays:
        row0:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
        row1:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
    - time: 1
      segment_displays:
        row0:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
        row1:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
  # beef:
  #   - duration: -1
  #     lights:
  #       l_status_rectangle_2: green
  #       l_status_rectangle_1: orange
  #       l_status_rectangle_0: yellow
  #       l_outlane_right: blue
  #       l_outlane_left: purple
  #       l_inlane_right: red
  #       l_inlane_left: white
    
show_player:
  mode_attract_started.1:
  # TODO: fix color wheel show because i had to fix light orders
    color_wheel:
      speed: 10
  mode_attract_started.2: attract_segment
    
  
