#config_version=5

slide_player:
  mode_attract_started.1:
    combined:
      target: window
  mode_attract_started.2:
    segment:
      target: normal
  mode_attract_started.3:
    background:
      target: background

shows:
  attract_segment:
    - time: 0
      segment_displays:
        row_0:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
        row_1:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
    - time: 1
      segment_displays:
        row_0:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
        row_1:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left


# shows:
#   rack_collect_test:
#     - time: 0
#       shows:
#         inverse_pulse_white:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_red:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_blue:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_purple:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_orange:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_green:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_pink:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_white:
#           loops: 0
#           speed: 40
#     - time: "+1"
#     - time: "+1"

show_player:
  mode_attract_started.1:
  # TODO: fix color wheel show because i had to fix light orders
    color_wheel:
      speed: 10
  mode_attract_started.2: attract_segment
