#config_version=5

slide_player:
  mode_attract_started.1:
    combined:
      target: window
  mode_attract_started.2:
    segment:
      target: normal
  mode_attract_started.3:
    background:
      target: background

shows:
  attract_segment:
    - time: 0
      segment_displays:
        row_0:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
        row_1:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
    - time: 1
      segment_displays:
        row_0:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
        row_1:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
  attract_planets:
    - time: 0
      shows:
        test_earth_scroll:
          loops: 0
          speed: 6
          priority: 10
    - time: "+3"
      shows:
        planet_shadow:
          loops: 0
          priority: 11
          speed: 10
          show_tokens:
            br_0: off
            br_1: off
            br_2: off
            br_3: "FF0000FF"
            fade: 150
    - time: "+1"
      shows:
        test_mars_scroll:
          loops: 0
          speed: 6
          priority: 10
    - time: "+3"
      shows:
        planet_shadow:
          loops: 0
          priority: 11
          speed: 10
          show_tokens:
            br_0: off
            br_1: off
            br_2: off
            br_3: "FF0000FF"
            fade: 150
    - time: "+1"
      shows:
        test_jupiter_scroll:
          loops: 0
          speed: 6
          priority: 10
    - time: "+3"
      shows:
        planet_shadow:
          loops: 0
          priority: 11
          speed: 10
          show_tokens:
            br_0: off
            br_1: off
            br_2: off
            br_3: "FF0000FF"
            fade: 150



# shows:
#   rack_collect_test:
#     - time: 0
#       shows:
#         inverse_pulse_white:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_red:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_blue:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_purple:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_orange:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_green:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_pink:
#           loops: 0
#           speed: 40
#     - time: "+1"
#       shows:
#         inverse_pulse_white:
#           loops: 0
#           speed: 40
#     - time: "+1"
#     - time: "+1"

show_player:
  mode_attract_started.1: attract_planets
  # mode_attract_started.1:
  #   color_wheel:
  #     speed: 10
      # TODO: fix color wheel show because i had to fix light orders
    # mars_success_2:
    #   priority: 10
    #   speed: 10
    #   show_tokens:
    #     color: red
    #     fade: 200
    #     planet_full: planet_full
    #     planet_medium: planet_medium
    #     planet_small: planet_small
    #     grid: grid
  # mode_attract_started.2:
  #   mars_surface_detail:
  #     priority: 11
  #     speed: 5
  #     show_tokens:
  #       color: red
  #       fade: 200
  #       br_0: "400000FF"
  #       br_1: "800000FF"
  #       br_2: "C00000FF"
  #       br_3: "FF0000FF"
  #       planet_full: planet_full
  #       planet_medium: planet_medium
  #       planet_small: planet_small
  #       grid: grid
  # trigger_planet_shadow:
  #   planet_shadow:
  #     # loops: 0
  #     loops: 0
  #     priority: 12
  #     speed: 12
  #     show_tokens:
  #       br_0: off
  #       br_1: off
  #       br_2: off
  #       br_3: "FF0000FF"
  #       fade: 150
      
  # #   # mars_surface_detail:
  # #   #   speed: 5
  # #   #   priority: 11
  # #   #   show_tokens:
  # #   #     br_0: "800000FF"
  # #   #     br_1: "800000FF"
  # #   #     br_2: "C00000FF"
  # #   #     br_3: "FF0000FF"
  # #   #     fade: 150
  mode_attract_started.2: attract_segment
