#config_version=5

slides:
  combined_slide:
    widgets:
      - type: display
        source_display: normal
        width: 1300
        height: 400
        effects:
          - type: glow
            blur_size: 5.0
            intensity: .6
            glow_speed: 1.0
            glow_amplitude: .2
      - type: display
        source_display: background
        width: 1300
        height: 400
  background_slide:
    widgets:
      - type: image
        image: bg1
        scale: 3
  segment_slide:
    target: normal
    widgets:
      - type: segment_display_emulator
        display_type: 14seg
        name: row0
        flash_mode: all
        flash_frequency: 7
        character_count: 16
        character_slant_angle: 5
        character_spacing: 20
        segment_width: 0.15
        segment_interval: 0.04
        segment_off_color: 4b4c4a30
        segment_on_color: FFFFFF
        side_bevel_enabled: true
        dot_enabled: false
        comma_enabled: false
        color: blue
        text: ""
        width: 1300
        height: 150
        opacity: 1
        x: 0
        y: 50
        anchor_x: left
        anchor_y: bottom
      - type: segment_display_emulator
        display_type: 14seg
        flash_mode: all
        flash_frequency: 7
        name: row1
        character_count: 16
        character_slant_angle: 5
        character_spacing: 20
        segment_width: 0.15
        segment_interval: 0.04
        segment_off_color: 4b4c4a30
        segment_on_color: FFFFFF
        side_bevel_enabled: true
        dot_enabled: false
        comma_enabled: false
        text: ""
        width: 1300
        height: 150
        x: 0
        y: 210
        anchor_x: left
        anchor_y: bottom

slide_player:
  mode_attract_started.1:
    combined_slide:
      target: window
  mode_attract_started.2:
    segment_slide:
      target: normal
  mode_attract_started.3:
    background_slide:
      target: background

shows:
  attract_segment:
    - time: 0
      segment_displays:
        row0:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
        row1:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
    - time: 1
      segment_displays:
        row0:
          color: white
          text: "PRESS START     "
          transition:
            type: push
            direction: right
        row1:
          color: white
          text: "     PRESS START"
          transition:
            type: push
            direction: left
  # beef:
  #   - duration: -1
  #     lights:
  #       l_status_rectangle_2: green
  #       l_status_rectangle_1: orange
  #       l_status_rectangle_0: yellow
  #       l_outlane_right: blue
  #       l_outlane_left: purple
  #       l_inlane_right: red
  #       l_inlane_left: white
    
show_player:
  mode_attract_started.1:
  # TODO: fix color wheel show because i had to fix light orders
    color_wheel:
      speed: 10
  mode_attract_started.2: attract_segment
    
  
