#config_version=5

slides:
  attract:
    widgets:
      - type: text
        text: PRESS START

shows:
  broth:
    - duration: .1
      lights:
        l_standup_left_6_4: white
        l_standup_left_6_3: white
        l_standup_left_6_2: white
        l_standup_left_6_1: white
        l_standup_left_6_0: white
        l_standup_left_5_0: white
        l_standup_left_5_1: white
        l_standup_left_5_2: white
        l_standup_left_5_3: white
        l_standup_left_5_4: white
        l_standup_left_4_4: white
        l_standup_left_4_3: white
        l_standup_left_4_2: white
        l_standup_left_4_1: white
        l_standup_left_4_0: white
        l_standup_left_3_0: white
        l_standup_left_3_1: white
        l_standup_left_3_2: white
        l_standup_left_3_3: white
        l_standup_left_3_4: white
        l_standup_left_2_4: white
        l_standup_left_2_3: white
        l_standup_left_2_2: white
        l_standup_left_2_1: white
        l_standup_left_2_0: white
        l_standup_left_1_0: white
        l_standup_left_1_1: white
        l_standup_left_1_2: white
        l_standup_left_1_3: white
        l_standup_left_1_4: white
    - duration: .1
      lights: 
        l_standup_left_6_4: green
        l_standup_left_6_3: green
        l_standup_left_6_2: green
        l_standup_left_6_1: green
        l_standup_left_6_0: green
        l_standup_left_5_0: green
        l_standup_left_5_1: green
        l_standup_left_5_2: green
        l_standup_left_5_3: green
        l_standup_left_5_4: green
        l_standup_left_4_4: green
        l_standup_left_4_3: green
        l_standup_left_4_2: green
        l_standup_left_4_1: green
        l_standup_left_4_0: green
        l_standup_left_3_0: green
        l_standup_left_3_1: green
        l_standup_left_3_2: green
        l_standup_left_3_3: green
        l_standup_left_3_4: green
        l_standup_left_2_4: green
        l_standup_left_2_3: green
        l_standup_left_2_2: green
        l_standup_left_2_1: green
        l_standup_left_2_0: green
        l_standup_left_1_0: green
        l_standup_left_1_1: green
        l_standup_left_1_2: green
        l_standup_left_1_3: green
        l_standup_left_1_4: green
  beef:
    - duration: .2
      lights:
        l_drop_upper: blue
        l_serial_chain_0_2: green
        l_serial_chain_0_3: blue
        l_serial_chain_0_4: green
        l_serial_chain_0_5: blue
        l_spinner_rectangle: red
        l_spinner_arrow_2: red
        l_spinner_arrow_1: red
        l_spinner_arrow_0: red
        l_serial_chain_0_10: green
        l_thin_standup_left: blue
        l_hook_1: green
        l_hook_0: blue
        l_thin_standup_right: green
        l_serial_chain_0_15: blue
        l_drop_left_rectangle_0: green
        l_drop_left_rectangle_1: blue
        l_drop_left_rectangle_2: green
        l_drop_left_rectangle_3: blue
        l_drop_left_rectangle_4: green
        l_drop_left_rectangle_5: blue
        l_drop_left_rectangle_6: green
        l_drop_left_arrow_0: blue
        l_drop_left_arrow_1: green
        l_drop_left_arrow_2: blue
        l_standup_left_6_4: white
        l_standup_left_6_3: white
        l_standup_left_6_2: white
        l_standup_left_6_1: white
        l_standup_left_6_0: white
        l_standup_left_5_0: white
        l_standup_left_5_1: white
        l_standup_left_5_2: white
        l_standup_left_5_3: white
        l_standup_left_5_4: white
        l_standup_left_4_4: white
        l_standup_left_4_3: white
        l_standup_left_4_2: white
        l_standup_left_4_1: white
        l_standup_left_4_0: white
        l_standup_left_3_0: white
        l_standup_left_3_1: white
        l_standup_left_3_2: white
        l_standup_left_3_3: white
        l_standup_left_3_4: white
        l_standup_left_2_4: white
        l_standup_left_2_3: white
        l_standup_left_2_2: white
        l_standup_left_2_1: white
        l_standup_left_2_0: white
        l_standup_left_1_0: white
        l_standup_left_1_1: white
        l_standup_left_1_2: white
        l_standup_left_1_3: white
        l_standup_left_1_4: white
        l_standup_left_0_0: white
        l_standup_left_0_1: white
        l_standup_left_0_2: white
        l_standup_left_0_3: white
        l_standup_left_0_4: white
        l_serial_chain_0_26: green
        l_serial_chain_0_27: blue 
        l_serial_chain_0_28: green
        l_serial_chain_0_29: blue
        l_serial_chain_0_30: green
        l_serial_chain_0_31: blue
        l_serial_chain_0_32: green
        l_status_circle_7: blue
        l_status_circle_6: green
        l_status_circle_5: blue
        l_status_circle_4: green
        l_status_circle_3: blue
        l_status_circle_2: green
        l_status_circle_1: blue
        l_status_circle_0: green
        l_ball_save: blue
    - duration: .2
      lights:
        l_drop_upper: green
        l_serial_chain_0_2: blue
        l_serial_chain_0_3: green
        l_serial_chain_0_4: blue
        l_serial_chain_0_5: green
        l_spinner_rectangle: yellow
        l_spinner_arrow_2: yellow
        l_spinner_arrow_1: yellow
        l_spinner_arrow_0: yellow
        l_serial_chain_0_10: blue
        l_thin_standup_left: green
        l_hook_1: blue
        l_hook_0: green
        l_thin_standup_right: blue
        l_serial_chain_0_15: green
        l_drop_left_rectangle_0: blue
        l_drop_left_rectangle_1: green
        l_drop_left_rectangle_2: blue
        l_drop_left_rectangle_3: green
        l_drop_left_rectangle_4: blue
        l_drop_left_rectangle_5: green
        l_drop_left_rectangle_6: blue
        l_drop_left_arrow_0: green
        l_drop_left_arrow_1: blue
        l_drop_left_arrow_2: green
        l_standup_left_6_4: off
        l_standup_left_6_3: off
        l_standup_left_6_2: off
        l_standup_left_6_1: off
        l_standup_left_6_0: off
        l_standup_left_5_0: off
        l_standup_left_5_1: off
        l_standup_left_5_2: off
        l_standup_left_5_3: off
        l_standup_left_5_4: off
        l_standup_left_4_4: off
        l_standup_left_4_3: off
        l_standup_left_4_2: off
        l_standup_left_4_1: off
        l_standup_left_4_0: off
        l_standup_left_3_0: off
        l_standup_left_3_1: off
        l_standup_left_3_2: off
        l_standup_left_3_3: off
        l_standup_left_3_4: off
        l_standup_left_2_4: off
        l_standup_left_2_3: off
        l_standup_left_2_2: off
        l_standup_left_2_1: off
        l_standup_left_2_0: off
        l_standup_left_1_0: off
        l_standup_left_1_1: off
        l_standup_left_1_2: off
        l_standup_left_1_3: off
        l_standup_left_1_4: off
        l_standup_left_0_0: off
        l_standup_left_0_1: off
        l_standup_left_0_2: off
        l_standup_left_0_3: off
        l_standup_left_0_4: off
        l_status_circle_7: green
        l_status_circle_6: blue
        l_status_circle_5: green
        l_status_circle_4: blue
        l_status_circle_3: green
        l_status_circle_2: blue
        l_status_circle_1: green
        l_status_circle_0: blue
        l_ball_save: green

show_player:
  mode_attract_started: beef

slide_player:
  mode_attract_started: attract
