#config_version=5

slides:
  attract:
    widgets:
      - type: text
        text: PRESS START

show_player:
  mode_attract_started:
    color_wheel:
      speed: 100

slide_player:
  mode_attract_started: attract
