#config_version=5

slides:
  attract:
    widgets:
      - type: text
        text: PRESS START

shows:
  beef:
  - duration: .2
    lights:
      l_drop_upper: blue
      l_serial_chain_0_2: green
      l_serial_chain_0_3: blue
      l_serial_chain_0_4: green
      l_serial_chain_0_5: blue
      l_spinner_rectangle: red
      l_spinner_arrow_2: red
      l_spinner_arrow_1: red
      l_spinner_arrow_0: red
      l_serial_chain_0_10: green
      l_thin_standup_left: blue
      l_hook_1: green
      l_hook_0: blue
      l_thin_standup_right: green
      l_serial_chain_0_15: blue
      l_drop_left_rectangle_0: green
      l_drop_left_rectangle_1: blue
      l_drop_left_rectangle_2: green
      l_drop_left_rectangle_3: blue
      l_drop_left_rectangle_4: green
      l_drop_left_rectangle_5: blue
      l_drop_left_rectangle_6: green
      l_drop_left_arrow_0: blue
      l_drop_left_arrow_1: green
      l_drop_left_arrow_2: blue
      l_serial_chain_0_26: green
      l_serial_chain_0_27: blue 
      l_serial_chain_0_28: green
      l_serial_chain_0_29: blue
      l_serial_chain_0_30: green
      l_serial_chain_0_31: blue
      l_serial_chain_0_32: green
      l_status_circle_7: blue
      l_status_circle_6: green
      l_status_circle_5: blue
      l_status_circle_4: green
      l_status_circle_3: blue
      l_status_circle_2: green
      l_status_circle_1: blue
      l_status_circle_0: green
      l_ball_save: blue

  - duration: .2
    lights:
      l_drop_upper: green
      l_serial_chain_0_2: blue
      l_serial_chain_0_3: green
      l_serial_chain_0_4: blue
      l_serial_chain_0_5: green
      l_spinner_rectangle: yellow
      l_spinner_arrow_2: yellow
      l_spinner_arrow_1: yellow
      l_spinner_arrow_0: yellow
      l_serial_chain_0_10: blue
      l_thin_standup_left: green
      l_hook_1: blue
      l_hook_0: green
      l_thin_standup_right: blue
      l_serial_chain_0_15: green
      l_drop_left_rectangle_0: blue
      l_drop_left_rectangle_1: green
      l_drop_left_rectangle_2: blue
      l_drop_left_rectangle_3: green
      l_drop_left_rectangle_4: blue
      l_drop_left_rectangle_5: green
      l_drop_left_rectangle_6: blue
      l_drop_left_arrow_0: green
      l_drop_left_arrow_1: blue
      l_drop_left_arrow_2: green
      l_serial_chain_0_26: blue
      l_serial_chain_0_27: green
      l_serial_chain_0_28: blue
      l_serial_chain_0_29: green
      l_serial_chain_0_30: blue
      l_serial_chain_0_31: green
      l_serial_chain_0_32: blue
      l_status_circle_7: green
      l_status_circle_6: blue
      l_status_circle_5: green
      l_status_circle_4: blue
      l_status_circle_3: green
      l_status_circle_2: blue
      l_status_circle_1: green
      l_status_circle_0: blue
      l_ball_save: green

show_player:
  mode_attract_started: beef

slide_player:
  mode_attract_started: attract
