#config_version=5

mode:
  start_events: ball_starting


segment_display_player:
  timer_base_start_complete.1:
    row_0:
      text: "{players[0].score:<16}"
  timer_base_start_complete.2:
    row_0:
      text: "{players[0].score:<16}"
    row_1:
      text: "          Ball {players[0].ball:d}"

timers:
  base_start:
    start_running: True
    end_value: 1
    tick_interval: 100ms
    control_events:
      - action: stop
        event: timer_base_start_complete
      - action: reset
        event: timer_base_start_complete
        
slide_player:
  mode_base_started.1:
    combined:
      target: window
  mode_base_started.2:
    segment:
      target: normal
  mode_base_started.3:
    background:
      target: background
