#config_version=5

mode:
  start_events: ball_starting

slides:
  base:
    widgets:
      - type: text
        text: (score)
        y: 100
      - type: text
        text: (player)
        y: 200

slide_player:
  mode_base_started: base

variable_player:
  s_pop_1_active:
    score: 100
  s_pop_2_active:
    score: 100
  s_pop_3_active:
    score: 100
