#config_version=5

mode:
  start_events: ball_starting

slides:
  base:
    widgets:
      - type: text
        text: BALL (ball)
        z: 10
        y: 0
        x: right
        anchor_x: right
        anchor_y: bottom
      - type: text
        text: SCORE (score)
        y: 100
      - type: text
        text: PLAYER (player)
        y: 200

slide_player:
  mode_base_started: base

timers:
  base_drop_right:
    end_value: 15
    tick_interval: 100ms
    control_events:
      - action: start
        event: s_hook_active
      - action: reset
        event: timer_base_drop_right_complete
  base_drop_left:
    end_value: 35
    tick_interval: 100ms
    control_events:
      - action: start
        event: s_hook_active
      - action: reset
        event: timer_base_drop_left_complete

event_player:
  s_drop_left_active{device.timers.base_drop_left.running==False}: reset_drop_left

# variable_player:
#   s_pop_0_active:
#     score: 100
#   s_pop_1_active:
#     score: 100
#   s_pop_2_active:
#     score: 100
#   s_sling_left_active:
#     score: 1000
#   s_sling_right_active:
#     score: 1000

