#config_version=5

mode:
  start_events: start_mball_locked
  stop_events: start_mball
  code: mball_locked.MballLocked

event_player:
  s_drops_upper_2_active: start_mball
    
variable_player:
  mode_mball_locked_started:
    mball_progress:
      int: 0
      action: set
