#config_version=5

mode:
  start_events: start_mball_qualifying
  stop_events: start_mball_locked

shows:
  mball_qualifying_none_qualified:
    - lights:
        (l0): (color)
        (l1): (color)
        (l2): (color)
    - lights:
        (l0): off
        (l1): off
        (l2): off
  mball_qualifying_one_qualified:
    - lights:
        (l0): (color)
        (l1): (color)
        (l2): (color)
    - lights:
        (l0): (color)
        (l1): off
        (l2): off
  mball_qualifying_two_qualified:
    - lights:
        (l0): (color)
        (l1): (color)
        (l2): (color)
    - lights:
        (l0): (color)
        (l1): (color)
        (l2): off
  mball_qualifying_lock_qualified:
    - duration: -1
      lights:
        (l0): (color)
        (l1): (color)
        (l2): (color)

shot_profiles:
  qualify_lock:
    states:
      - name: none_qualified
        show: mball_qualifying_none_qualified
        speed: 10
      - name: one_qualified
        show: mball_qualifying_one_qualified
        speed: 10
      - name: two_qualified
        show: mball_qualifying_two_qualified
        speed: 10
      - name: lock_qualified
        show: mball_qualifying_lock_qualified
        
  lock:
    states:
      - name: unlit
        show: off
      - name: lit
        show: flash_color
        speed: 10

shots:
  sh_qualify_lock:
    hit_events: sh_orbit_left_drop_hit
    reset_events: start_mball_locked
    advance_events: mball_qualifying_advance_progress_1, mball_qualifying_advance_progress_2
    profile: qualify_lock
    show_tokens:
      l0: l_spinner_arrow_0
      l1: l_spinner_arrow_1
      l2: l_spinner_arrow_2
      color: green
  sh_lock:
    switch: s_scoop
    advance_events: mball_qualifying_lock_qualified
    profile: lock
    reset_events: start_mball_locked
    show_tokens:
      light: l_drop_upper
      color: green

variable_player:
  sh_qualify_lock_hit:
    mball_progress: 1

event_player:
  mode_mball_qualifying_started{current_player.mball_progress==2 and current_player.shot_sh_qualify_lock==0}:
    - mball_qualifying_advance_progress_1
    - mball_qualifying_advance_progress_2
  mode_mball_qualifying_started{current_player.mball_progress==1 and current_player.shot_sh_qualify_lock==0}:
    - mball_qualifying_advance_progress_1
  mode_mball_qualifying_started{current_player.shot_sh_qualify_lock<3}: activate_drop_upper
  mode_mball_qualifying_started{current_player.shot_sh_qualify_lock>=3}: mball_qualifying_lock_qualified, deactivate_drop_upper

  # progression
  sh_qualify_lock_hit{current_player.shot_sh_qualify_lock<3}: activate_drop_upper
  sh_qualify_lock_hit{current_player.shot_sh_qualify_lock>=3}: mball_qualifying_lock_qualified, deactivate_drop_upper
  sh_orbit_left_scoop_hit: start_mball_locked

