#config_version=5

# Mode for managing drop target related logic

mode:
  start_events: ball_starting

timers:
  drops_raise_right:
    end_value: 2
    control_events:
      - action: start
        event: start_saucer_shot_timers
      - action: reset
        event: timer_drops_raise_right_complete
  drops_lower_left:
    end_value: 5
    control_events:
      - action: start
        event: start_saucer_shot_timers
      - action: reset
        event: timer_drops_lower_left_complete
      - action: stop
        event: saucer_hit
      - action: reset
        event: saucer_hit

event_player:
  # init, leaving upper drop init to multiball mode
  mode_drops_started:
    - activate_drop_left
    - deactivate_drop_right

  # resetting left
  s_drop_left_active{device.timers.drops_lower_left.running==False}: activate_drop_left

  timer_drops_raise_right_complete: deactivate_drop_right
  timer_drops_lower_left_complete: activate_drop_left
  saucer_hit: activate_drop_left

  # keyboard control
  s_force_knockdown_coils_active:
    - deactivate_drop_left
    - deactivate_drop_right
    - deactivate_drop_upper
