#config_version=5

mode:
  start_events: ball_starting
  code: spinner.Spinner

state_machines:
  spinner:
    starting_state: off
    states:
      off:
        label: spinner shot not qualified
        events_when_started: spinner_state_off_started
      qualified:
        label: spinner shot is ready to be hit, untimed
        events_when_started: spinner_state_qualified_started
      qualified_timed:
        label: spinner shot is ready to be hit, timed
        events_when_started: spinner_state_qualified_timed_started
      spinning_off:
        label: odd number of spins
        events_when_started: spinner_state_spinning_off_started
      spinning_on:
        label: initial hit and all other even number of spins
        events_when_started: spinner_state_spinning_on_started
    transitions:
      - source: off
        target: qualified_timed
        events: s_inlane_right_active
      - source: off
        target: qualified
        events: spinner_qualified_from_award
      - source: qualified
        target: spinning_off
        events: s_spinner_active
      - source: qualified_timed
        target: spinning_off
        events: s_spinner_active
      - source: spinning_off
        target: spinning_on
        events: s_spinner_active
      - source: spinning_on
        target: spinning_off
        events: s_spinner_active
        # timeouts
      - source: qualified_timed
        target: off
        events: timer_spinner_qualified_timeout_complete
      - source: spinning_off
        target: off
        events: timer_spinner_spinning_timeout_complete
      - source: spinning_on
        target: off
        events: timer_spinner_spinning_timeout_complete
      - source: spinning_off
        target: off
        events: timer_spinner_spinning_timeout_complete
        # TODO: add ball ending transitions too

shot_profiles:
  spinner:
    advance_on_hit: False
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color
      - name: spinning_on
        show: led_color
      - name: spinning_off
        show: off

shots:
  sh_spinner:
    switch: s_spinner
    # NOTE: Other shot profile updates happening in spinner.py
    advance_events: timer_spinning_started
    profile: spinner
    show_tokens:
      light: l_spinner_rectangle
      color: pink

timers:
  spinner_spinning_timeout:
    end_value: 3
    control_events:
      - action: start
        event: spinner_state_spinning_off_started
      - action: reset
        event: spinner_state_spinning_off_started
      - action: reset
        event: spinner_state_spinning_on_started
      - action: reset
        event: timer_spinner_spinning_timeout_complete
  spinner_qualified_timeout:
    end_value: 10
    control_events:
      - action: start
        event: spinner_state_qualified_timed_started
      - action: reset
        event: timer_spinner_qualified_timeout_complete

sound_player:
  s_spinner_active: spin_0
