#config_version=5

mode:
  start_events: ball_starting
  code: awards.Awards

shot_profiles:
  awards_qualify_collect:
    states:
      - name: flash
        show: flash_color
        speed: 10
        show_tokens:
          color: orange
  awards_collect:
    states:
      - name: flash
        show: flash_color
        speed: 10
        show_tokens:
          color: orange
  awards_select:
    states:
      - name: lit
        show: led_color
        show_tokens:
          color: orange
  awards:
    states:
      - name: off
        show: off
      - name: lit
        show: led_color
        show_tokens:
          color: orange
      - name: flash
        show: flash_color
        show_tokens:
          color: orange
        speed: 10

shots:
  sh_awards_qualify_collect:
    switch: s_hook
    profile: awards_qualify_collect
    enable_events: mode_awards_started, timer_drops_lower_left_complete
    disable_events: timer_drops_lower_left_started
    show_tokens:
      light: l_hook_0
  sh_awards_collect:
    profile: awards_collect
    enable_events: timer_drops_lower_left_started
    disable_events: mode_awards_started, timer_drops_lower_left_complete
    # TODO: have to handle this in code due to timing
    # hit_events: sh_saucer_debounced_hit
    show_tokens:
      light: l_drop_left_arrow_0
  sh_awards_select_left:
    profile: awards_select
    switch: s_thin_standup_left
    show_tokens:
      light: l_thin_standup_left
  sh_awards_select_right:
    profile: awards_select
    switch: s_thin_standup_right
    show_tokens:
      light: l_thin_standup_right
  sh_awards_6:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_0
  sh_awards_5:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_1
  sh_awards_4:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_2
  sh_awards_3:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_3
  sh_awards_2:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_4
  sh_awards_1:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_5
  sh_awards_0:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_6

event_player:
  sh_awards_qualify_collect_hit:
    - activate_drop_right
    - deactivate_drop_left
    - start_saucer_shot_timers
