#config_version=5

mode:
  start_events: ball_starting
  code: awards.Awards

# steps:
# make sure i can select an awards and it cycles
# logic for awards qualifying

shot_profiles:
  awards_collect:
    states:
      - name: flash
        show: flash_stop
        speed: 6
  awards_select:
    states:
      - name: lit
        show: on
  awards:
    states:
      - name: off
        show: off
      - name: on
        show: on
      - name: flash
        show: flash_stop
        speed: 10

shots:
  # sh_awards_collect:
  #   switch: s_scoop_lower
  #   profile: awards_collect
  #   enable_events: timer_awards_collect_started
  #   disable_events: timer_awards_collect_complete, sh_awards_collect_hit
  #   show_tokens:
  #     light: l_scoop_lower_1
  sh_awards_select_left:
    profile: awards_select
    switch: s_thin_standup_left
    show_tokens:
      light: l_thin_standup_left
  sh_awards_select_right:
    profile: awards_select
    switch: s_thin_standup_right
    show_tokens:
      light: l_thin_standup_right
  sh_awards_0:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_0
  sh_awards_1:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_1
  sh_awards_2:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_2
  sh_awards_3:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_3
  sh_awards_4:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_4
  sh_awards_5:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_5
  sh_awards_6:
    profile: awards
    show_tokens:
      light: l_drop_left_rectangle_6
  
# timers:
#   awards_collect:
#     end_value: 5
#     control_events:
#       - action: start
#         event: s_hook_active
#       - action: reset
#         event: timer_awards_collect_complete
#       - action: reset
#         event: sh_awards_collect_hit
