#config_version=5

mode:
  start_events: ball_starting

shows:
  none_lit:
    - duration: -1 
      lights:
        (a): off
        (b): off
        (c): off
        (d): off
  one_lit:
    - duration: -1 
      lights:
        (a): on
        (b): off
        (c): off
        (d): off
  two_lit:
    - duration: -1 
      lights:
        (a): on
        (b): on
        (c): off
        (d): off
  three_lit:
    - duration: -1 
      lights:
        (a): on
        (b): on
        (c): on
        (d): off
  four_lit:
    - duration: -1 
      lights:
        (a): on
        (b): on
        (c): on
        (d): on

shot_profiles:
    left_target:
        states:
          - name: none_lit
            show: none_lit
          - name: one_lit
            show: one_lit
          - name: two_lit
            show: two_lit
          - name: three_lit
            show: three_lit
          - name: four_lit
            show: four_lit

shots:
  # right targets
  sh_target_right_0:
    hit_events: s_target_right_0_active
    show_tokens:
      light: l_target_right_0_0
  sh_target_right_1:
    hit_events: s_target_right_1_active
    show_tokens:
      light: l_target_right_1_0
  sh_target_right_2:
    hit_events: s_target_right_2_active
    show_tokens:
      light: l_target_right_2_0
  sh_target_right_3:
    hit_events: s_target_right_3_active
    show_tokens:
      light: l_target_right_3_0
