#config_version=5

mode:
  start_events: award_5_selected
  stop_events: award_5_unselected

# TODO: end this mode once the show is done playing
# TODO: add test so that show won't play twice if scratch guards are already activate
show_player:
  saucer_collect_award_show_start:
    instant_million:
      loops: 0
      speed: 1
      priority: 1000
      events_when_completed: award_x_show_complete

variable_player:
  saucer_collect_award_show_start:
    score: 1000000

