#config_version=5

# award_5 - outlane saves

mode:
  start_events: award_5_selected
  stop_events: award_0_selected, award_1_selected, award_2_selected, award_3_selected, award_4_selected, award_6_selected


