#config_version=5

mode:
  start_events: planets_earth_start
  stop_events: racks_collect_show_complete
  code: earth.Earth
  priority: 100
  
shot_profiles:
  earth:
    states:
      - name: flash
      - name: not_flash
  earth_l:
    states:
      - name: off
        show: stop
      - name: on
        show: on
      - name: flash
        show: flash
        speed: 10

shots:
  sh_earth_0:
    profile: earth
    hit_events: s_standup_left_0_active
  sh_earth_1:
    profile: earth
    hit_events: s_standup_left_1_active
  sh_earth_2:
    profile: earth
    hit_events: s_standup_left_2_active
  sh_earth_3:
    profile: earth
    hit_events: s_standup_left_3_active
  sh_earth_4:
    profile: earth
    hit_events: s_standup_left_4_active
  sh_earth_5:
    profile: earth
    hit_events: s_standup_left_5_active
  sh_earth_6:
    profile: earth
    hit_events: s_standup_left_6_active
  sh_earth_l_0_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_0_0
  sh_earth_l_0_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_0_1
  sh_earth_l_0_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_0_2
  sh_earth_l_0_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_0_3
  sh_earth_l_0_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_0_4
  sh_earth_l_1_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_1_0
  sh_earth_l_1_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_1_1
  sh_earth_l_1_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_1_2
  sh_earth_l_1_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_1_3
  sh_earth_l_1_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_1_4
  sh_earth_l_2_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_2_0
  sh_earth_l_2_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_2_1
  sh_earth_l_2_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_2_2
  sh_earth_l_2_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_2_3
  sh_earth_l_2_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_2_4
  sh_earth_l_3_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_3_0
  sh_earth_l_3_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_3_1
  sh_earth_l_3_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_3_2
  sh_earth_l_3_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_3_3
  sh_earth_l_3_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_3_4
  sh_earth_l_4_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_4_0
  sh_earth_l_4_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_4_1
  sh_earth_l_4_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_4_2
  sh_earth_l_4_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_4_3
  sh_earth_l_4_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_4_4
  sh_earth_l_5_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_5_0
  sh_earth_l_5_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_5_1
  sh_earth_l_5_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_5_2
  sh_earth_l_5_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_5_3
  sh_earth_l_5_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_5_4
  sh_earth_l_6_0:
    profile: earth_l
    show_tokens:
      light: l_standup_left_6_0
  sh_earth_l_6_1:
    profile: earth_l
    show_tokens:
      light: l_standup_left_6_1
  sh_earth_l_6_2:
    profile: earth_l
    show_tokens:
      light: l_standup_left_6_2
  sh_earth_l_6_3:
    profile: earth_l
    show_tokens:
      light: l_standup_left_6_3
  sh_earth_l_6_4:
    profile: earth_l
    show_tokens:
      light: l_standup_left_6_4

show_player:
  # note hte slightly higher priority so the doublehits will show first
  sh_racks_5_6_6_hit:
    pulse_standup_left_6:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_5_6_5_hit:
    pulse_standup_left_5:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_4_5_5_hit:
    pulse_standup_left_5:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_4_5_4_hit:
    pulse_standup_left_4:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_3_4_4_hit:
    pulse_standup_left_4:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_3_4_3_hit:
    pulse_standup_left_3:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_2_3_3_hit:
    pulse_standup_left_3:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_2_3_2_hit:
    pulse_standup_left_2:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_1_2_2_hit:
    pulse_standup_left_2:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_1_2_1_hit:
    pulse_standup_left_1:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_0_1_1_hit:
    pulse_standup_left_1:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  sh_racks_0_1_0_hit:
    pulse_standup_left_0:
      loops: 0
      speed: 35
      priority: 11
      sync_ms: 50
  # normal pulse shows
  sh_racks_6_hit:
    pulse_standup_left_6:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_5_hit:
    pulse_standup_left_5:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_4_hit:
    pulse_standup_left_4:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_3_hit:
    pulse_standup_left_3:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_2_hit:
    pulse_standup_left_2:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_1_hit:
    pulse_standup_left_1:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50
  sh_racks_0_hit:
    pulse_standup_left_0:
      loops: 0
      speed: 35
      priority: 10
      sync_ms: 50

sound_player:
  sh_racks_0_hit: zap_0
  sh_racks_1_hit: zap_1
  sh_racks_2_hit: zap_2
  sh_racks_3_hit: zap_3
  sh_racks_4_hit: zap_4
  sh_racks_5_hit: zap_5
  sh_racks_6_hit: zap_6
