#config_version=5

mode:
  start_events: ball_starting

variable_player:
  s_sling_left_active:
    score: 1000
  s_sling_right_active:
    score: 1000

show_player:
  s_sling_left_active:
    pulse_sling_left:
      loops: 0
      speed: 50
      priority: 10
  s_sling_right_active:
    pulse_sling_right:
      loops: 0
      speed: 50
      priority: 10
  
sound_player:
  s_sling_left_active: wobble
  s_sling_right_active: wobble
