#config_version=5

autofire_coils:
  # ac_sling_left:
  #   coil: c_sling_left
  #   switch: s_sling_left
  # ac_sling_right:
  #   coil: c_sling_right
  #   switch: s_sling_right
  pop_a:
    coil: c_pop_a
    switch: s_pop_a
  pop_b:
    coil: c_pop_b
    switch: s_pop_b
  pop_c:
    coil: c_pop_c
    switch: s_pop_c
