#config_version=5

autofire_coils:
  ac_sling_left:
    coil: c_sling_left
    switch: s_sling_left
    # enable_events: machine_reset_phase_3
  ac_sling_right:
    coil: c_sling_right
    switch: s_sling_right
    # enable_events: machine_reset_phase_3
  # ac_sling_left_lower:
  #   coil: c_sling_left
  #   switch: s_sling_left_lower
  #   # enable_events: machine_reset_phase_3
  # ac_sling_right_lower:
  #   coil: c_sling_right
  #   switch: s_sling_right_lower
  #   # enable_events: machine_reset_phase_3
  pop_center:
    coil: c_pop_center
    switch: s_pop_center
  pop_left:
    coil: c_pop_left
    switch: s_pop_left
  pop_right:
    coil: c_pop_right
    switch: s_pop_right
