#config_version=5

autofire_coils:
  ac_sling_left_upper:
    coil: c_sling_left
    switch: s_sling_left_upper
  ac_sling_right_upper:
    coil: c_sling_right
    switch: s_sling_right_upper
  ac_sling_left_lower:
    coil: c_sling_left
    switch: s_sling_left_lower
  ac_sling_right_lower:
    coil: c_sling_right
    switch: s_sling_right_lower
  pop_center:
    coil: c_pop_center
    switch: s_pop_center
  pop_left:
    coil: c_pop_left
    switch: s_pop_left
  pop_right:
    coil: c_pop_right
    switch: s_pop_right
