#config_version=5

ball_devices:
  bd_trough:
    ball_switches: s_trough_0, s_trough_1 #, s_trough_jam
    eject_coil: c_trough_eject
    mechanical_eject: False
    tags: drain, home, trough
    eject_targets: bd_plunger
#    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: True
    eject_coil: c_plunger_eject
    player_controlled_eject_event: s_launch_active
    eject_timeouts: 5s
  bd_saucer:
    ball_switches: s_saucer
    eject_coil: c_saucer
    entrance_count_delay: 1000ms
    eject_targets: playfield
    target_on_unexpected_ball: playfield
    confirm_eject_switch: s_inlane_left
    confirm_eject_type: switch
  bd_scoop:
    ball_switches: s_scoop
    eject_coil: c_scoop
    entrance_count_delay: 2s
    eject_timeouts: 3s

  # bd_scoop_lower:
  #   ball_switches: s_scoop_lower
  #   eject_coil: c_scoop_lower
  #   entrance_count_delay: 2s
  #   eject_timeouts: 3s
