#config_version=5

ball_devices:
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3
    eject_coil: c_trough_eject
    tags: drain, home, trough
    eject_targets: bd_plunger
    entrance_count_delay: 300ms
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger_eject
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    player_controlled_eject_event: s_launch
    debug: True
