#config_version=5

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: ball_starting
    early_ball_save_events: s_outlane_left_active, s_outlane_right_active
    timer_start_events: balldevice_bd_plunger_ball_eject_success, s_orbit_active
    auto_launch: yes
    balls_to_save: 1
