#config_version=5

coils:
  # c_flipper_lower_left_main:
  #   number: A1-B0-0
  #   default_pulse_ms: 23
  # c_flipper_lower_left_hold:
  #   number: A1-B0-1
  #   default_hold_power: .4
  #   allow_enable: true
  # c_flipper_lower_right_main:
  #   number: A1-B0-2
  #   default_pulse_ms: 23
  # c_flipper_lower_right_hold:
  #   number: A1-B0-3
  #   allow_enable: true
  #   default_hold_power: .4
  # c_flipper_mid_right_main:
  #   number: A1-B1-2
  #   default_pulse_ms: 15
  # c_flipper_mid_right_hold:
  #   number: A1-B1-3
  #   allow_enable: true
  #   default_hold_power: .65
  # c_flipper_upper_right_main:
  #   number: A1-B1-4
  #   default_pulse_ms: 15
  # c_flipper_upper_right_hold:
  #   number: A1-B1-5
  #   default_hold_power: .5
  #   allow_enable: true
  # c_pop_a:
  #   number: A3-B0-0
  #   default_pulse_power: 0.95
  # c_pop_b:
  #   number: A3-B0-1
  #   default_pulse_power: 0.95
  # c_pop_c:
  #   number: A3-B0-2
  #   default_pulse_power: 0.95
  # c_diverter_left:
  #   number: A3-B0-3
  #   default_hold_power: .5
  #   allow_enable: true
  # c_diverter_right:
  #   number: A3-B0-4
  #   default_hold_power: .5
  #   allow_enable: true
  c_scoop_eject:
    number: A3-B1-0
    default_pulse_ms: 100
  c_trough_eject:
    number: coil1
    default_pulse_ms: 100
  c_plunger_eject:
    number: coil2
    default_pulse_ms: 100
  c_pop_1:
    number: coil3
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_pop_2:
    number: coil4
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_pop_3:
    number: coil5
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_sling_left:
    number: coil6
    default_pulse_ms: 100
  c_sling_right:
    number: coil7
    default_pulse_ms: 100
  c_diverter_hook:
    number: coil8
    default_hold_power: 0.25
    allow_enable: true
