#config_version=5

coils:
  c_trough_eject:
    number: coil1
    default_pulse_ms: 100
  c_plunger_eject:
    number: coil2
    default_pulse_ms: 100
  c_pop_0:
    number: coil3
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_pop_1:
    number: coil4
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_pop_2:
    number: coil5
    default_pulse_power: 0.95
    default_pulse_ms: 100
  c_sling_left:
    number: coil6
    default_pulse_ms: 100
  c_sling_right:
    number: coil7
    default_pulse_ms: 100
  c_diverter_hook:
    number: coil8
    default_hold_power: 0.25
    allow_enable: true
  c_drops_upper_1:
    number: coil9
    default_hold_power: 0.25
    allow_enable: true
  c_drops_upper_2:
    number: coil10
    default_hold_power: 0.25
    allow_enable: true
  c_drops_upper_3:
    number: coil11
    default_hold_power: 0.25
    allow_enable: true
  c_scoop_upper:
    number: coil12
    default_pulse_ms: 100
  c_scoop_lower:
    number: coil13
    default_pulse_ms: 100
