#config_version=5

coils:
  # Board 6 (Lower)
  c_plunger_eject:
    number: A6-B1-0
    default_pulse_ms: 12
  c_trough_eject:
    number: A6-B1-1
    default_pulse_ms: 40
  c_flipper_right_main:
    number: A6-B1-2
    default_pulse_ms: 33
  c_flipper_right_hold:
    number: A6-B1-3
    default_hold_power: 1
  c_flipper_left_main:
    number: A6-B1-4
    default_pulse_ms: 33
  c_flipper_left_hold:
    number: A6-B1-5
    default_hold_power: 1
  c_sling_right:
    number: A6-B1-6
    default_pulse_ms: 6
  c_sling_left:
    number: A6-B1-7
    default_pulse_ms: 6
  c_flipper_upper_main:
    number: A6-B0-0
    default_pulse_ms: 23 # 38
  c_flipper_upper_hold:
    number: A6-B0-1
    default_hold_power: 1 #0.2
    # default_pulse_ms: 17
  c_drop_right_knockdown:
    number: A6-B0-2
    default_pulse_ms: 12
  c_drop_right:
    number: A6-B0-3
    default_pulse_ms: 25
  # Board 7 (Upper)
  c_scoop:
    number: A7-B0-0
    default_pulse_ms: 9
  c_drop_upper_knockdown:
    number: A7-B0-1
    default_pulse_ms: 15
  c_drop_upper:
    number: A7-B0-2
    default_pulse_ms: 25
  c_pop_right:
    number: A7-B1-0
    default_pulse_ms: 17
    default_recycle: False
  c_pop_center:
    number: A7-B1-1
    default_pulse_ms: 17
    default_recycle: False
  c_pop_left:
    number: A7-B1-2
    default_pulse_ms: 17
    default_recycle: False
  c_drop_left_knockdown:
    number: A7-B1-3
    default_pulse_ms: 15
  c_drop_left:
    number: A7-B1-4
    default_pulse_ms: 18
  c_saucer:
    number: A7-B1-5
    default_pulse_ms: 65 #was 40
