#config_version=5

config:
- assets.yaml
- autofire_coils.yaml
- ball_devices.yaml
- ball_saves.yaml
- coils.yaml
- displays.yaml
- drop_targets.yaml
- flippers.yaml
- hardware.yaml
- keyboard.yaml
- lights.yaml
- machine_vars.yaml
- modes.yaml
- p_roc.yaml
- player_vars.yaml
- playfields.yaml
- segment_displays.yaml
- shot_profiles.yaml
- slides.yaml
- sound_loop_sets.yaml
- sound_pools.yaml
- sound_system.yaml
- sounds.yaml
- switches.yaml
- virtual_platform_start_active_switches.yaml
- virtual_segment_display_connector.yaml
- window.yaml
