#config_version=5


# hardware:
#   platform: virtual_pinball
hardware:
  platform: p3_roc
  driverboards: pdb

virtual_platform_start_active_switches:
  - s_trough_0
  - s_trough_1
  - s_trough_2

p_roc:
  pd_led_boards:
    8:
      use_ws281x_0: True
      ws281x_0_last_address: 327

config:
- autofire_coils.yaml
- ball_devices.yaml
- ball_saves.yaml
- coils.yaml
- drop_targets.yaml
- flippers.yaml
- keyboard.yaml
- lights.yaml
# # - machine_vars.yaml
- modes.yaml
- player_vars.yaml
- playfields.yaml
- switches.yaml

# create configs for sound stuff
sound_system:
  master_volume: 1.5
  tracks:
     # music:
     #   type: sound_loop
     #   simultaneous_sounds: 1
     #   volume: 0.5
     # voice:
     #   type: standard
     #   simultaneous_sounds: 1
     #   volume: 0.7
     sfx:
       type: standard
       simultaneous_sounds: 32
       volume: 1
       preload: yes
     loops:
       type: sound_loop
       volume: 1
       preload: yes

assets:
  sounds:
    # default:
    #   load: on_demand
    # music:
    #   track: music
    #   # preload for testing purposes only
    #   load: preload
    sfx:
      track: sfx
      load: preload
    loops:
      track: loops
      load: preload
    # voice:
    #   track: voice

sounds:
  target_collected_0:
    max_queue_time: 0
  target_collected_ogg_0:
    max_queue_time: 0
  loop_target_collected:
    max_queue_time: 0
  loop_target_collected_2:
    max_queue_time: 0
  # target_collected_0:
  #   max_queue_time: 5ms
  # target_collected_ogg_0:
  #   max_queue_time: 5ms


sound_loop_sets:
  rack_collected:
    sound: loop_target_collected_2
    tempo: 937.5

window:
    width: 1300
    height: 400
    source_display: window
    effects:
      - type: glow
        blur_size: 5.0
        intensity: .6
        glow_speed: 1.0
        glow_amplitude: .2
        
# segment_displays:
#   row0:
#     number: 1
#     size: 16
#     # platform: virtual
#   row1:
#     number: 1
#     size: 16
#     # platform: virtual

# virtual_segment_display_connector:
#   segment_displays: row0, row1
    
displays:
  window:
     width: 1300
     height: 400
  # normal:
  #    width: 1300
  #    height: 400
  # background:
  #    width: 1300
  #    height: 400
