#config_version=5
diverters:
  div_right:
    activation_coil: c_diverter_hook
    type: hold
    activation_time: 2s
    activation_switches: s_hook_release
    enable_events: ball_started
    disable_events: ball_ended
    debug: True

