#config_version=5
diverters:
  div_right:
    activation_coil: c_diverter_hook
    type: hold
    activation_time: 2s
    activation_switches: s_hook_release
    enable_events: ball_starting
    disable_events: ball_ended
  div_drops_upper_1:
    activation_coil: c_drops_upper_1
    type: hold
    activate_events: ball_started, mball_activate_drop_1
    deactivate_events: s_drops_upper_1_active, mball_deactivate_drop_1
    enable_events: ball_starting
    disable_events: ball_ended
  div_drops_upper_2:
    activation_coil: c_drops_upper_2
    type: hold
    activate_events: ball_started, mball_activate_drop_2
    deactivate_events: s_drops_upper_2_active, mball_deactivate_drop_2
    enable_events: ball_starting
    disable_events: ball_ended
  div_drops_upper_3:
    activation_coil: c_drops_upper_3
    type: hold
    activate_events: ball_started, mball_activate_drop_3
    deactivate_events: s_drops_upper_3_active, mball_deactivate_drop_3
    enable_events: ball_starting
    disable_events: ball_ended
    
