#config_version=5

drop_targets:
  drop_right:
    switch: s_hook
    reset_coil: c_smart_drop_right
    reset_events: s_hook_active
    knockdown_events: timer_smart_drop_right_complete
    knockdown_coil: c_smart_drop_right_knockdown
  # drop_saucer:
  #   switch: s_saucer_drop
  #   reset_coil: c_saucer_drop
  #   # reset_events: ball_starting
  #   reset_events: ball_starting, timer_drop_saucer_complete, reset_saucer_drop
  #   knockdown_events: s_hook_1_active
  #   knockdown_coil: c_saucer_drop_knockdown
    

# drop_target_banks:
#   drops:
#     drop_targets: d_a

# drop_target_banks:
#   # posts event drop_target_bank_drops_down when all down
#   drops:
#     drop_targets: d_a,d_b,d_c
#     reset_coils: c_drops
#     # reset_events: drops_state_reset_bank

