#config_version=5

drop_targets:
  smart_drop_right:
    switch: s_hook
    reset_coil: c_smart_drop_right
    reset_events: sh_racks_qualify_collect_hit
    knockdown_events: ball_starting, timer_smart_drop_right_complete, s_force_knockdown_coils_active
    knockdown_coil: c_smart_drop_right_knockdown
  smart_drop_left:
    switch: s_smart_drop_left
    reset_coil: c_smart_drop_left
    reset_events: ball_starting, timer_smart_drop_left_complete, reset_smart_drop_left
    knockdown_events: s_hook_active, s_force_knockdown_coils_active
    knockdown_coil: c_smart_drop_left_knockdown
  smart_drop_upper:
    switch: s_smart_drop_upper
    reset_coil: c_smart_drop_upper
    reset_events: ball_starting, timer_smart_drop_left_complete, reset_smart_drop_upper
    knockdown_coil: c_smart_drop_upper_knockdown
    knockdown_events: s_force_knockdown_coils_active

    # reset_events: ball_starting

# drop_target_banks:
#   drops:
#     drop_targets: d_a

# drop_target_banks:
#   # posts event drop_target_bank_drops_down when all down
#   drops:
#     drop_targets: d_a,d_b,d_c
#     reset_coils: c_drops
#     # reset_events: drops_state_reset_bank

