#config_version=5

drop_targets:
  right:
    switch: s_drop_right
    reset_coil: c_drop_right
    knockdown_coil: c_drop_right_knockdown
    reset_events: activate_drop_right
    knockdown_events: deactivate_drop_right, test_knockdown_right
  left:
    switch: s_drop_left
    reset_coil: c_drop_left
    knockdown_coil: c_drop_left_knockdown
    reset_events: activate_drop_left
    knockdown_events: deactivate_drop_left, test_knockdown_left
  upper:
    switch: s_drop_upper
    reset_coil: c_drop_upper
    knockdown_coil: c_drop_upper_knockdown
    reset_events: activate_drop_upper
    knockdown_events: deactivate_drop_upper, test_knockdown_upper, balldevice_bd_scoop_ejecting_ball
