#config_version=5

flippers:
  flipper_left:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
  flipper_right:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right
  flipper_upper: 
    main_coil: c_flipper_upper
    activation_switch: s_flipper_right

