#config_version=5

keyboard:
  s:
    switch: s_start
  f:
    switch: s_force_knockdown_coils
  t:
    switch: s_trough_0
    toggle: True
  b:
    switch: s_force_ball_save
  o:
    switch: s_orbit
  # i:
  #   switch: s_right_inlane
  p:
    switch: s_plunger_lane
  # d:
  #   event: drop_target_bank_drops_down
  # l:
  #   event: dev_award_letter
  n:
    event: s_thin_standup_left
  m:
    event: s_thin_standup_right
