#config_version=5

keyboard:
  s:
    switch: s_start
  f:
    switch: s_force_knockdown_coils
  a:
    switch: s_flipper_left
  d:
    switch: s_flipper_right
  t:
    event: scratch_guards_start
  b:
    switch: s_force_ball_save
  o:
    switch: s_orbit
  # lanes
  j:
    switch: s_outlane_left
  k:
    switch: s_inlane_left
  l:
    switch: s_inlane_right
  ;:
    switch: s_outlane_right
  i:
    switch: s_spinner
  p:
    switch: s_plunger_lane
  v:
    switch: s_saucer
    toggle: True
  h:
    switch: s_hook
  n:
    switch: s_thin_standup_left
  m:
    switch: s_thin_standup_right
  0:
    switch: s_standup_left_0
  1:
    switch: s_standup_left_1
  2:
    switch: s_standup_left_2
  3:
    switch: s_standup_left_3
  4:
    switch: s_standup_left_4
  5:
    switch: s_standup_left_5
  6:
    switch: s_standup_left_6
  7:
    switch: s_standup_left_7
  u:
    switch: s_standup_upper
  e:
    event: test_event
