#config_version=5

light_settings:
  default_fade_ms: 100
  default_color_correction_profile: correction_profile
  color_correction_profiles:
    correction_profile:
      whitepoint: [1.0, 1.0, 1.0]
      gamma: 2.5
      linear_slope: 1.0
      linear_cutoff: 0.0

lights:
  l_drop_upper:
    number: 8-100-101-102
    subtype: led
    type: grb
  l_lane_left:
    number: 8-103-104-105
    subtype: led
    type: grb
  l_lane_center:
    number: 8-106-107-108
    subtype: led
    type: grb
  l_lane_right:
    number: 8-109-110-111
    subtype: led
    type: grb
  l_standup_upper:
    number: 8-112-113-114
    subtype: led
    type: grb
  l_spinner_rectangle:
    number: 8-115-116-117
    subtype: led
    type: grb
  l_spinner_arrow_2:
    number: 8-118-119-120
    subtype: led
    type: grb
  l_spinner_arrow_1:
    number: 8-121-122-123
    subtype: led
    type: grb
  l_spinner_arrow_0:
    number: 8-124-125-126
    subtype: led
    type: grb
  l_standup_center:
    number: 8-127-128-129
    subtype: led
    type: grb
  l_thin_standup_left:
    number: 8-130-131-132
    subtype: led
    type: grb
  l_hook_1:
    number: 8-133-134-135
    subtype: led
    type: grb
  l_hook_0:
    number: 8-136-137-138
    subtype: led
    type: grb
  l_thin_standup_right:
    number: 8-139-140-141
    subtype: led
    type: grb
  # drop right
  l_drop_right:
    number: 8-142-143-144
    subtype: led
    type: grb
  l_drop_left_rectangle_0:
    number: 8-145-146-147
    subtype: led
    type: grb
  l_drop_left_rectangle_1:
    number: 8-148-149-150
    subtype: led
    type: grb
  l_drop_left_rectangle_2:
    number: 8-151-152-153
    subtype: led
    type: grb
  l_drop_left_rectangle_3:
    number: 8-154-155-156
    subtype: led
    type: grb
  l_drop_left_rectangle_4:
    number: 8-157-158-159
    subtype: led
    type: grb
  l_drop_left_rectangle_5:
    number: 8-160-161-162
    subtype: led
    type: grb
  l_drop_left_rectangle_6:
    number: 8-163-164-165
    subtype: led
    type: grb
  # drop left arrow 1
  l_drop_left_arrow_0:
    number: 8-166-167-168
    subtype: led
    type: grb
  # drop left arrow 2
  l_drop_left_arrow_1:
    number: 8-169-170-171
    subtype: led
    type: grb
  # drop left arrow 3
  l_drop_left_arrow_2:
    number: 8-172-173-174
    subtype: led
    type: grb
  l_standup_left_6_4:
    number: 8-175-176-177
    subtype: led
    type: rgb
  l_standup_left_6_3:
    number: 8-178-179-180
    subtype: led
    type: rgb
  l_standup_left_6_2:
    number: 8-181-182-183
    subtype: led
    type: rgb
  l_standup_left_6_1:
    number: 8-184-185-186
    subtype: led
    type: rgb
  l_standup_left_6_0:
    number: 8-187-188-189
    subtype: led
    type: rgb
  l_standup_left_5_0:
    number: 8-190-191-192
    subtype: led
    type: rgb
  l_standup_left_5_1:
    number: 8-193-194-195
    subtype: led
    type: rgb
  l_standup_left_5_2:
    number: 8-196-197-198
    subtype: led
    type: rgb
  l_standup_left_5_3:
    number: 8-199-200-201
    subtype: led
    type: rgb
  l_standup_left_5_4:
    number: 8-202-203-204
    subtype: led
    type: rgb
  l_standup_left_4_4:
    number: 8-205-206-207
    subtype: led
    type: rgb
  l_standup_left_4_3:
    number: 8-208-209-210
    subtype: led
    type: rgb
  l_standup_left_4_2:
    number: 8-211-212-213
    subtype: led
    type: rgb
  l_standup_left_4_1:
    number: 8-214-215-216
    subtype: led
    type: rgb
  l_standup_left_4_0:
    number: 8-217-218-219
    subtype: led
    type: rgb
  l_standup_left_3_0:
    number: 8-220-221-222
    subtype: led
    type: rgb
  l_standup_left_3_1:
    number: 8-223-224-225
    subtype: led
    type: rgb
  l_standup_left_3_2:
    number: 8-226-227-228
    subtype: led
    type: rgb
  l_standup_left_3_3:
    number: 8-229-230-231
    subtype: led
    type: rgb
  l_standup_left_3_4:
    number: 8-232-233-234
    subtype: led
    type: rgb
  l_standup_left_2_4:
    number: 8-235-236-237
    subtype: led
    type: rgb
  l_standup_left_2_3:
    number: 8-238-239-240
    subtype: led
    type: rgb
  l_standup_left_2_2:
    number: 8-241-242-243
    subtype: led
    type: rgb
  l_standup_left_2_1:
    number: 8-244-245-246
    subtype: led
    type: rgb
  l_standup_left_2_0:
    number: 8-247-248-249
    subtype: led
    type: rgb
  l_standup_left_1_0:
    number: 8-250-251-252
    subtype: led
    type: rgb
  l_standup_left_1_1:
    number: 8-253-254-255
    subtype: led
    type: rgb
  l_standup_left_1_2:
    number: 8-256-257-258
    subtype: led
    type: rgb
  l_standup_left_1_3:
    number: 8-259-260-261
    subtype: led
    type: rgb
  l_standup_left_1_4:
    number: 8-262-263-264
    subtype: led
    type: rgb

  l_standup_left_0_4:
    number: 8-265-266-267
    subtype: led
    type: rgb
  l_standup_left_0_3:
    number: 8-268-269-270
    subtype: led
    type: rgb
  l_standup_left_0_2:
    number: 8-271-272-273
    subtype: led
    type: rgb
  l_standup_left_0_1:
    number: 8-274-275-276
    subtype: led
    type: rgb
  l_standup_left_0_0:
    number: 8-277-278-279
    subtype: led
    type: rgb

  # rectangle lower 3
  l_status_rectangle_2:
    number: 8-280-281-282
    subtype: led
    type: grb
  # rectangle lower 2
  l_status_rectangle_1:
    number: 8-283-284-285
    subtype: led
    type: grb
  # rectangle lower 1
  l_status_rectangle_0:
    number: 8-286-287-288
    subtype: led
    type: grb
  # outlane right
  l_outlane_right:
    number: 8-289-290-291
    subtype: led
    type: grb
  # inlane right
  l_inlane_right:
    number: 8-292-293-294
    subtype: led
    type: grb
  # inlane left
  l_inlane_left:
    number: 8-295-296-297
    subtype: led
    type: grb
  # outlane left
  l_outlane_left:
    number: 8-298-299-300
    subtype: led
    type: grb
  l_status_circle_7:
    number: 8-301-302-303
    subtype: led
    type: grb
  l_status_circle_6:
    number: 8-304-305-306
    subtype: led
    type: grb
  l_status_circle_5:
    number: 8-307-308-309
    subtype: led
    type: grb
  l_status_circle_4:
    number: 8-310-311-312
    subtype: led
    type: grb
  l_status_circle_3:
    number: 8-313-314-315
    subtype: led
    type: grb
  l_status_circle_2:
    number: 8-316-317-318
    subtype: led
    type: grb
  l_status_circle_1:
    number: 8-319-320-321
    subtype: led
    type: grb
  l_status_circle_0:
    number: 8-322-323-324
    subtype: led
    type: grb
  l_ball_save:
    number: 8-325-326-327
    subtype: led
    type: grb
