#config_version=5

lights:
  # lanes
  l0:
    number: l1
    subtype: led
  l1:
    number: l2
    subtype: led
  l2:
    number: l3
    subtype: led
  # right targets
  l_target_right_0_0:
    number: l4
    subtype: led
  l_target_right_1_0:
    number: l5
    subtype: led
  l_target_right_2_0:
    number: l6
    subtype: led
  l_target_right_3_0:
    number: l7
    subtype: led
  # left targets
  l_target_left_0_0:
    number: l8
    subtype: led
  l_target_left_0_1:
    number: l9
    subtype: led
  l_target_left_0_2:
    number: 20
    subtype: led
  l_target_left_0_3:
    number: 21
    subtype: led
  l_target_left_1_0:
    number: 22
    subtype: led
  l_target_left_1_1:
    number: 23
    subtype: led
  l_target_left_1_2:
    number: 24
    subtype: led
  l_target_left_1_3:
    number: 25
    subtype: led
  l_target_left_2_0:
    number: 26
    subtype: led
  l_target_left_2_1:
    number: 27
    subtype: led
  l_target_left_2_2:
    number: 28
    subtype: led
  l_target_left_2_3:
    number: 29
    subtype: led
  l_target_left_3_0:
    number: 30
    subtype: led
  l_target_left_3_1:
    number: 31
    subtype: led
  l_target_left_3_2:
    number: 32
    subtype: led
  l_target_left_3_3:
    number: 33
    subtype: led
  l_target_left_4_0:
    number: 34
    subtype: led
  l_target_left_4_1:
    number: 35
    subtype: led
  l_target_left_4_2:
    number: 36
    subtype: led
  l_target_left_4_3:
    number: 37
    subtype: led
  l_target_left_5_0:
    number: 38
    subtype: led
  l_target_left_5_1:
    number: 39
    subtype: led
  l_target_left_5_2:
    number: 40
    subtype: led
  l_target_left_5_3:
    number: 41
    subtype: led
  l_target_left_6_0:
    number: 42
    subtype: led
  l_target_left_6_1:
    number: 43
    subtype: led
  l_target_left_6_2:
    number: 44
    subtype: led
  l_target_left_6_3:
    number: 45
    subtype: led
  l_outlane_left_0:
    number: 46
    subtype: led
  l_inlane_left_0:
    number: 47
    subtype: led
  l_inlane_right_0:
    number: 48
    subtype: led
  l_outlane_right_0:
    number: 49
    subtype: led
  l_spinner_right_0:
    number: 50
    subtype: led
    tags: l_spinner_right
  l_spinner_right_1:
    number: 51
    subtype: led
    tags: l_spinner_right
  l_spinner_right_2:
    number: 52
    subtype: led
    tags: l_spinner_right
  l_spinner_right_3:
    number: 53
    subtype: led
    tags: l_spinner_right
  l_ball_save:
    number: 54
    subtype: led
  l_scoop_lower_0:
    number: 55
    subtype: led
