#config_version=5

modes:
  # testing
  # - test

  # utility
  # - slide_listener
  # - autostack

  # global
  - base
  - ball_save
  - lanes
  # - targets
  - spinners
  - multiball_config
  - mball_startup
  - mball_qualifying
  - mball_locked
  - mball
  - racks

  # ball end
  # - bonus
