#config_version=5

modes:
  # testing
  # - test

  # utility
  # - slide_listener
  # - autostack

  # generic
  - base
  - ball_save
  - saucer
  - drops
  # game specific modes
  - spinner
  - scratch_guards
  - multiball_config
  - mball_startup
  - mball_qualifying
  - mball_locked
  - mball
  - racks
  - multicue
  # - spot_ball
  - awards
  - award_0
  - award_1
  - award_2
  - award_3
  - award_4
  - award_5
  - award_6
  - orbit_left

  # ball end
  # - bonus
