#config_version=5

modes:
  # testing
  # - test

  # utility
  # - slide_listener
  # - autostack

  # global
  - base
  - ball_save
  # - lanes
  # - spinners
  - multiball_config
  - mball_startup
  - mball_qualifying
  - mball_locked
  - mball
  - racks
  # - wide_shot
  # - spot_ball
  # - awards

  # ball end
  # - bonus
