#config_version=5

modes:
  # testing
  # - test

  # utility
  # - slide_listener
  # - autostack

  # global
  - base
  - ball_save
  - lanes
  - targets
  - spinners
  - mball

  # ball end
  # - bonus
