#config_version=5

modes:
  - award_0
  - award_1
  - award_2
  - award_3
  - award_4
  - award_5
  - award_6
  - awards
  - ball_save
  - base
  - base_bonus
  - drops
  - lanes_upper
  - jackpot
  - mball
  - mball_locked
  - mball_qualifying
  - mball_startup
  - multiball_config
  - multicue
  - orbit_left
  - pops
  - racks
  - saucer
  - scratch_guards
  - slings
  - spinner
  # - bonus
