#config_version=5

modes:
  - announcer
  - award_0
  - award_1
  - award_2
  - award_3
  - award_4
  - award_5
  - award_6
  - awards
  - ball_save
  - base
  - base_bonus
  - drops
  - earth
  - jackpot
  - lanes_upper
  - mars
  - mball
  - mball_locked
  - mball_qualifying
  - mball_startup
  - multiball_config
  - multicue
  - orbit_left
  - planets
  - pops
  - racks
  - saucer
  - sequencer
  - scratch_guards
  - slings
  - spinner

