#config_version=5

modes:
  # testing
  # - test

  # utility
  # - slide_listener
  # - autostack

  - base
  - base_bonus
  - ball_save
  - saucer
  - drops
  - spinner
  - scratch_guards
  - multiball_config
  - mball_startup
  - mball_qualifying
  - mball_locked
  - mball
  - racks
  - multicue
  - awards
  - award_0
  - award_1
  - award_2
  - award_3
  - award_4
  - award_5
  - award_6
  - orbit_left
  - lanes_upper

  # ball end
  # - bonus
