#config_version=5

player_vars:
  bonus_x:
    initial_value: 1
  mball_progress:
    initial_value: 2
  mballs_played:
    initial_value: 0
  planets:
    initial_value: 0
  # earth target left progress
  earth_0_progress:
    initial_value: 0
  earth_1_progress:
    initial_value: 0
  earth_2_progress:
    initial_value: 0
  earth_3_progress:
    initial_value: 0
  earth_4_progress:
    initial_value: 0
  earth_5_progress:
    initial_value: 0
  earth_6_progress:
    initial_value: 0
  # earth target left progress
  mars_hurry_up_completed:
    initial_value: 0
  mars_earth_enabled:
    initial_value: 0
  mars_0_progress:
    initial_value: 0
  mars_1_progress:
    initial_value: 0
  mars_2_progress:
    initial_value: 0
  mars_3_progress:
    initial_value: 0
  mars_4_progress:
    initial_value: 0
  mars_5_progress:
    initial_value: 0
  mars_6_progress:
    initial_value: 0
  # earth target left progress
  mars_earth_0_progress:
    initial_value: 0
  mars_earth_1_progress:
    initial_value: 0
  mars_earth_2_progress:
    initial_value: 0
  mars_earth_3_progress:
    initial_value: 0
  mars_earth_4_progress:
    initial_value: 0
  mars_earth_5_progress:
    initial_value: 0
  mars_earth_6_progress:
    initial_value: 0

  # wide shot
  multicue_position:
    initial_value: 3
  # awards collected
  award_sets:
    initial_value: 0
  award_selected:
    initial_value: 3
  award_0_collected:
    initial_value: 0
  award_1_collected:
    initial_value: 0
  award_2_collected:
    initial_value: 0
  award_3_collected:
    initial_value: 0
  award_4_collected:
    initial_value: 0
  award_5_collected:
    initial_value: 0
  award_6_collected:
    initial_value: 0
