#config_version=5

player_vars:
  mball_progress:
    initial_value: 2
  mballs_played:
    initial_value: 0
  racks:
    initial_value: 0
  # target left progress
  tl_0_progress:
    initial_value: 0
  tl_1_progress:
    initial_value: 0
  tl_2_progress:
    initial_value: 0
  tl_3_progress:
    initial_value: 0
  tl_4_progress:
    initial_value: 0
  tl_5_progress:
    initial_value: 0
  tl_6_progress:
    initial_value: 0
  # wide shot
  wide_shot_progress:
    initial_value: 0
  wide_shot_position:
    initial_value: 4
  # awards collected
  award_selected:
    initial_value: 0
  award_0_collected:
    initial_value: 0
  award_1_collected:
    initial_value: 0
  award_2_collected:
    initial_value: 0
  award_3_collected:
    initial_value: 0
  award_4_collected:
    initial_value: 0
  award_5_collected:
    initial_value: 0
  award_6_collected:
    initial_value: 0
