#config_version=5

sound_system:
  master_volume: .75
  tracks:
     sfx:
       type: standard
       simultaneous_sounds: 32
       volume: 1
       preload: yes
     # TODO: May need to update this to not be preloaded
     loops:
       type: sound_loop
       volume: 1
       preload: yes

