#config_version=5

switches:
  # Virtual/Keyboard switches
  s_force_knockdown_coils:
    number: A11-B0-3
  s_force_ball_save:
    number: A11-B0-8
  s_start:
    number: A11-B0-7
    tags: start
  s_enter_playfield:
    number: A11-B0-6
    type: 'NC'
  s_launch:
    number: A11-B0-5
  s_drain:
    number: A11-B0-4
  # Board 0
  s_left_flipper:
    number: A0-B1-2
    tags: left_flipper
  s_right_flipper:
    number: A0-B1-7
    tags: right_flipper
  # Board 1
  s_trough_6:
    number: A1-B0-00
    type: 'NC'
  s_trough_5:
    number: A1-B0-01
    type: 'NC'
  s_trough_4:
    number: A1-B0-02
    type: 'NC'
  s_trough_3:
    number: A1-B0-03
    type: 'NC'
  s_trough_2:
    number: A1-B0-04
    type: 'NC'
  s_trough_1:
    number: A1-B0-05
    type: 'NC'
  s_trough_jam:
    number: A1-B0-06
    type: 'NC'
  s_plunger_lane:
    number: A1-B0-07
  s_outlane_left:
    number: A1-B1-0
  s_inlane_left:
    number: A1-B1-1
  # s_sling_left_lower:
  #   number: A1-B1-2
  s_sling_left:
    number: A1-B1-2
  s_sling_right:
    number: A1-B1-4
  # s_sling_right_lower:
  #   number: A1-B1-5
  s_inlane_right:
    number: A1-B1-6
  s_outlane_right:
    number: A1-B1-7
  # Board 2 (Center Playfield)
  s_thin_standup_left:
    number: A2-B0-0
  s_thin_standup_right:
    number: A2-B0-1
  s_drop_right:
    number: A2-B0-2
  s_hook:
    number: A2-B0-3
  s_standup_upper:
    number: A2-B0-4
  s_orbit:
    number: A2-B0-5
    tags: playfield_active
  s_standup_left_0:
    number: A2-B1-0
  s_standup_left_1:
    number: A2-B1-1
  s_standup_left_2:
    number: A2-B1-2
  s_standup_left_3:
    number: A2-B1-3
  s_standup_left_4:
    number: A2-B1-4
  s_standup_left_5:
    number: A2-B1-5
  s_standup_left_6:
    number: A2-B1-6
  # Board 3 (Upper Playfield)
  s_drop_left:
    number: A3-B0-0
  s_saucer:
    number: A3-B0-1
  s_standup_center:
    number: A3-B0-2
  s_pop_center:
    number: A3-B0-3
    debounce: quick
  s_pop_right:
    number: A3-B0-4
    debounce: quick
  s_pop_left:
    number: A3-B0-5
    debounce: quick
  s_scoop:
    number: A3-B1-0
    type: NC
  s_drop_upper:
    number: A3-B1-1
  s_upper_lane_right:
    number: A3-B1-2
  s_upper_lane_center:
    number: A3-B1-3
  s_upper_lane_left:
    number: A3-B1-4
