#config_version=5

switches:
  s_start:
    number: 0
    tags: start
  s_enter_playfield:
    number: 1
    type: 'NC'
  s_launch:
    number: 2
  s_drain:
    number: 3
  s_plunger:
    number: 4
  s_left_flipper:
    number: 5
    tags: left_flipper
  s_right_flipper:
    number: 6
    tags: right_flipper
  s_trough_1:
    number: 7
  s_trough_2:
    number: 8
  s_trough_3:
    number: 9
  s_pop_1:
    number: 10
  s_pop_2:
    number: 11
  s_pop_3:
    number: 12
  s_lane_upper_2:
    number: 14
  s_lane_upper_3:
    number: 15
  s_lane_upper_1:
    number: 13
  s_target_right_1:
    number: 16
  s_target_right_2:
    number: 17
  s_target_right_3:
    number: 18
  s_target_right_4:
    number: 19
  s_target_left_1:
    number: 20
  s_target_left_2:
    number: 21
  s_target_left_3:
    number: 22
  s_target_left_4:
    number: 23
  s_target_left_5:
    number: 24
  s_target_left_6:
    number: 25
  s_target_left_7:
    number: 26
  
