#config_version=5

switches:
  s_start:
    number: A11-B0-7 #doesnt exit
    tags: start
  s_enter_playfield:
    number: A11-B0-6 #doesnt exit
    type: 'NC'
  s_launch:
    number: A11-B0-5 #doesnt exit
  # s_drain:
  #   number: 3
  s_plunger_lane:
    number: A11-B0-4 #doesnt exit
  s_left_flipper:
    number: A0-B0-0
    tags: left_flipper
  s_right_flipper:
    number: A0-B0-1
    tags: right_flipper
  s_trough_0:
    number: A11-B0-1 #doesnt exit
  s_trough_1:
    number: A11-B0-2 #doesnt exit
  s_trough_2:
    number: A11-B0-3 #doesnt exit
  # s_pop_0:
  #   number: 10
  # s_pop_1:
  #   number: 11
  # s_pop_2:
  #   number: 12
  # s_lane_upper_0:
  #   number: 13
  # s_lane_upper_1:
  #   number: 14
  # s_lane_upper_2:
  #   number: 15
  # s_target_right_0:
  #   number: 16
  # s_target_right_1:
  #   number: 17
  # s_target_right_2:
  #   number: 18
  # s_target_right_3:
  #   number: 19
  # s_target_left_0:
  #   number: 20
  # s_target_left_1:
  #   number: 21
  # s_target_left_2:
  #   number: 22
  # s_target_left_3:
  #   number: 23
  # s_target_left_4:
  #   number: 24
  # s_target_left_5:
  #   number: 25
  # s_target_left_6:
  #   number: 26
  # s_outlane_left:
  #   number: 27
  # s_inlane_left:
  #   number: 28
  # s_inlane_right:
  #   number: 29
  # s_outlane_right:
  #   number: 30
  # s_sling_left:
  #   number: 31
  # s_sling_right:
  #   number: 32
  # s_hook_release:
  #   number: 33
  # s_drops_upper_0:
  #   number: 34
  # s_drops_upper_1:
  #   number: 35
  # s_drops_upper_2:
  #   number: 36
  # s_scoop_upper:
  #   number: 37
  # s_scoop_lower:
  #   number: 38
  # s_spinner_right:
  #   number: 39
