#config_version=5

# when first row of racks is down, the scoop lights to collect

mode:
  start_events: ball_starting
  code: racks.Racks
  priority: 100

shot_profiles:
  racks_status:
    states:
      - name: unlit
        show: off
      - name: current
        show: flash_color
        speed: 6
      - name: collected
        show: led_color
  racks_qualify_collect:
    states:
      - name: flash
        show: flash
        speed: 6
  racks_collect:
    states:
      - name: flash
        show: flash
        speed: 6
  l:
    states:
      - name: off
        show: off
      - name: on
        show: on
      - name: flash
        show: flash
        speed: 6

shots:
  sh_racks_status_0:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_0
      color: blue
  sh_racks_status_1:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_1
      color: blue
  sh_racks_status_2:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_2
      color: blue
  sh_racks_status_3:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_3
      color: blue
  sh_racks_status_4:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_4
      color: blue
  sh_racks_status_5:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_5
      color: blue
  sh_racks_status_6:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_6
      color: blue
  sh_racks_status_7:
    profile: racks_status
    start_enabled: True
    show_tokens:
      light: l_status_circle_7
      color: blue
  sh_racks_qualify_collect:
    profile: racks_qualify_collect
    enable_events: racks_enable_qualify_collect
    disable_events: racks_rack_collected, sh_racks_qualify_collect_hit
    switch: s_hook
    show_tokens:
      light: l_hook_1
  sh_racks_collect:
    profile: racks_collect
    enable_events: sh_racks_qualify_collect_hit
    disable_events: racks_rack_collected, timer_base_drop_left_complete
    # Have to handle this in code
    # hit_events: sh_saucer_debounced_hit
    show_tokens:
      light: l_drop_left_arrow_1
  sh_tl_0:
    hit_events: s_standup_left_0_active, spot_ball_0
  sh_tl_1:
    hit_events: s_standup_left_1_active, spot_ball_1
  sh_tl_2:
    hit_events: s_standup_left_2_active, spot_ball_2
  sh_tl_3:
    hit_events: s_standup_left_3_active, spot_ball_3
  sh_tl_4:
    hit_events: s_standup_left_4_active, spot_ball_4
  sh_tl_5:
    hit_events: s_standup_left_5_active, spot_ball_5
  sh_tl_6:
    hit_events: s_standup_left_6_active, spot_ball_6
  l_0_0:
    profile: l
    show_tokens:
      light: l_standup_left_0_0
  l_0_1:
    profile: l
    show_tokens:
      light: l_standup_left_0_1
  l_0_2:
    profile: l
    show_tokens:
      light: l_standup_left_0_2
  l_0_3:
    profile: l
    show_tokens:
      light: l_standup_left_0_3
  l_0_4:
    profile: l
    show_tokens:
      light: l_standup_left_0_4
  l_1_0:
    profile: l
    show_tokens:
      light: l_standup_left_1_0
  l_1_1:
    profile: l
    show_tokens:
      light: l_standup_left_1_1
  l_1_2:
    profile: l
    show_tokens:
      light: l_standup_left_1_2
  l_1_3:
    profile: l
    show_tokens:
      light: l_standup_left_1_3
  l_1_4:
    profile: l
    show_tokens:
      light: l_standup_left_1_4
  l_2_0:
    profile: l
    show_tokens:
      light: l_standup_left_2_0
  l_2_1:
    profile: l
    show_tokens:
      light: l_standup_left_2_1
  l_2_2:
    profile: l
    show_tokens:
      light: l_standup_left_2_2
  l_2_3:
    profile: l
    show_tokens:
      light: l_standup_left_2_3
  l_2_4:
    profile: l
    show_tokens:
      light: l_standup_left_2_4
  l_3_0:
    profile: l
    show_tokens:
      light: l_standup_left_3_0
  l_3_1:
    profile: l
    show_tokens:
      light: l_standup_left_3_1
  l_3_2:
    profile: l
    show_tokens:
      light: l_standup_left_3_2
  l_3_3:
    profile: l
    show_tokens:
      light: l_standup_left_3_3
  l_3_4:
    profile: l
    show_tokens:
      light: l_standup_left_3_4
  l_4_0:
    profile: l
    show_tokens:
      light: l_standup_left_4_0
  l_4_1:
    profile: l
    show_tokens:
      light: l_standup_left_4_1
  l_4_2:
    profile: l
    show_tokens:
      light: l_standup_left_4_2
  l_4_3:
    profile: l
    show_tokens:
      light: l_standup_left_4_3
  l_4_4:
    profile: l
    show_tokens:
      light: l_standup_left_4_4
  l_5_0:
    profile: l
    show_tokens:
      light: l_standup_left_5_0
  l_5_1:
    profile: l
    show_tokens:
      light: l_standup_left_5_1
  l_5_2:
    profile: l
    show_tokens:
      light: l_standup_left_5_2
  l_5_3:
    profile: l
    show_tokens:
      light: l_standup_left_5_3
  l_5_4:
    profile: l
    show_tokens:
      light: l_standup_left_5_4
  l_6_0:
    profile: l
    show_tokens:
      light: l_standup_left_6_0
  l_6_1:
    profile: l
    show_tokens:
      light: l_standup_left_6_1
  l_6_2:
    profile: l
    show_tokens:
      light: l_standup_left_6_2
  l_6_3:
    profile: l
    show_tokens:
      light: l_standup_left_6_3
  l_6_4:
    profile: l
    show_tokens:
      light: l_standup_left_6_4

# TODO: move this 
event_player:
  mode_racks_started{current_player.racks==0}: racks_collected_0
  racks_rack_collected{current_player.racks==1}: racks_collected_1
  # s_drop_upper_active{device.timers.drop_left.running == False}: reset_drop_upper
