#config_version=5

# when first row of racks is down, the scoop lights to collect

mode:
  start_events: ball_starting
  code: racks.Racks
  priority: 100

shot_profiles:
  racks_qualify_collect:
    states:
      - name: flash
        show: flash
        speed: 6
  racks_collect:
    states:
      - name: flash
        show: flash
        speed: 6
  l:
    states:
      - name: off
        show: off
      - name: on
        show: on
      - name: flash
        show: flash
        speed: 6

shots:
  sh_racks_qualify_collect:
    profile: racks_qualify_collect
    enable_events: racks_enable_qualify_collect
    disable_events: racks_rack_collected, sh_racks_qualify_collect_hit
    switch: s_hook
    show_tokens:
      light: l_hook_2
  sh_racks_collect:
    profile: racks_collect
    enable_events: sh_racks_qualify_collect_hit
    disable_events: racks_rack_collected, timer_smart_drop_left_complete
    switch: s_saucer
    show_tokens:
      light: l_drop_left_arrow_2
  sh_tl_0:
    hit_events: s_standup_left_0_active, spot_ball_0
  sh_tl_1:
    hit_events: s_standup_left_1_active, spot_ball_1
  sh_tl_2:
    hit_events: s_standup_left_2_active, spot_ball_2
  sh_tl_3:
    hit_events: s_standup_left_3_active, spot_ball_3
  sh_tl_4:
    hit_events: s_standup_left_4_active, spot_ball_4
  sh_tl_5:
    hit_events: s_standup_left_5_active, spot_ball_5
  sh_tl_6:
    hit_events: s_standup_left_6_active, spot_ball_6
  l_0_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_0_0
  l_0_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_0_1
  l_0_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_0_2
  l_0_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_0_3
  l_1_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_1_0
  l_1_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_1_1
  l_1_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_1_2
  l_1_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_1_3
  l_2_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_2_0
  l_2_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_2_1
  l_2_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_2_2
  l_2_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_2_3
  l_3_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_3_0
  l_3_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_3_1
  l_3_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_3_2
  l_3_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_3_3
  l_4_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_4_0
  l_4_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_4_1
  l_4_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_4_2
  l_4_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_4_3
  l_5_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_5_0
  l_5_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_5_1
  l_5_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_5_2
  l_5_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_5_3
  l_6_0:
    profile: l
    # show_tokens:
    #   light: l_target_left_6_0
  l_6_1:
    profile: l
    # show_tokens:
    #   light: l_target_left_6_1
  l_6_2:
    profile: l
    # show_tokens:
    #   light: l_target_left_6_2
  l_6_3:
    profile: l
    # show_tokens:
    #   light: l_target_left_6_3
    
timers:
  smart_drop_right:
    end_value: 15
    tick_interval: 100ms
    control_events:
      - action: start
        event: sh_racks_qualify_collect_hit
      - action: reset
        event: timer_smart_drop_right_complete
  smart_drop_left:
    end_value: 35
    tick_interval: 100ms
    control_events:
      - action: start
        event: sh_racks_qualify_collect_hit
      - action: reset
        event: timer_smart_drop_left_complete

# TODO: move this 
event_player:
  s_smart_drop_left_active{device.timers.smart_drop_left.running == False}: reset_smart_drop_left
  # s_smart_drop_upper_active{device.timers.smart_drop_left.running == False}: reset_smart_drop_upper
