#config_version=5

mode:
  start_events: ball_starting

shows:
  lanes_upper_complete:
    - time: 0
      lights:
        l_lane_left: red
        l_lane_center: red
        l_lane_right: red
    - time: "+1"
      lights:
        l_lane_left: off
        l_lane_center: off
        l_lane_right: off

shots:
  sh_lanes_upper_left:
    switch: s_upper_lane_left
    profile: ebb_default
    show_tokens:
      light: l_lane_left
      color: red
  sh_lanes_upper_center:
    switch: s_upper_lane_center
    profile: ebb_default
    show_tokens:
      light: l_lane_center
      color: red
  sh_lanes_upper_right:
    switch: s_upper_lane_right
    profile: ebb_default
    show_tokens:
      light: l_lane_right
      color: red

variable_player:
  lanes_upper_lit_complete:
    bonus_x: 1

show_player:
  lanes_upper_lit_complete:
    lanes_upper_complete:
      loops: 5
      speed: 10

shot_groups:
  lanes_upper:
    shots: sh_lanes_upper_left, sh_lanes_upper_center, sh_lanes_upper_right
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active
    reset_events: lanes_upper_lit_complete

event_player:
  lanes_upper_lit_complete: increment_bonus_x
  
