#config_version=5

mode:
  start_events: ball_starting
  code: multicue.Multicue

shows:
  multicue_on:
    - duration: -1
      lights:
        (light): on
    
shot_profiles:
  multicue:
    states:
      - name: unlit
        show: stop
      - name: lit
        show: led_color
        show_tokens:
          color: yellow
  multicue_activate:
    states:
      - name: flash
        show: flash_color
        speed: 10
        show_tokens:
          color: yellow

shots:
  sh_multicue:
    switch: s_standup_upper
    start_enabled: True
    enable_events: multicue_collected
    disable_events: multicue_qualified
    profile: multicue_activate
    show_tokens:
      light: l_standup_upper
      color: yellow
  # 'shots' for lights on grid
  sh_multicue_0:
    profile: multicue
    show_tokens:
      light: l_standup_left_0_4
  sh_multicue_1:
    profile: multicue
    show_tokens:
      light: l_standup_left_1_4
  sh_multicue_2:
    profile: multicue
    show_tokens:
      light: l_standup_left_2_4
  sh_multicue_3:
    profile: multicue
    show_tokens:
      light: l_standup_left_3_4
  sh_multicue_4:
    profile: multicue
    show_tokens:
      light: l_standup_left_4_4
  sh_multicue_5:
    profile: multicue
    show_tokens:
      light: l_standup_left_5_4
  sh_multicue_6:
    profile: multicue
    show_tokens:
      light: l_standup_left_6_4

event_player:
  sh_multicue_hit:  multicue_qualified
