#config_version=5

mode:
  start_events: ball_starting
  code: spot_ball.SpotBall

shot_profiles:
  spot_ball:
    states:
      - name: flash
        show: flash
        speed: 10

shots:
  sh_spot_ball:
    switch: s_target_right_3
    profile: spot_ball
    show_tokens:
      light: l_target_right_3_0

