#config_version=5

mode:
  start_events: ball_starting
  code: wide_shot.WideShot
  priority: 200

shows:
  wsl_on:
    - duration: -1
      lights:
        (light): on
    
shot_profiles:
  wsl:
    states:
      - name: unlit
        show: off
      - name: flash
        show: flash_color
        speed: 6
        show_tokens:
          color: yellow
      - name: lit
        show: led_color
        show_tokens:
          color: yellow
  wide_shot:
    states:
      - name: flash
        show: flash_color
        speed: 6
        show_tokens:
          color: yellow

shots:
  sh_wide_shot:
    switch: s_standup_upper
    disable_events: wide_shot_qualified, wide_shot_init_disable
    enable_events: wide_shot_collected, wide_shot_init_enable
    profile: wide_shot
    show_tokens:
      light: l_standup_upper
      color: yellow
  # 'shots' for lights on grid
  sh_wsl_0:
    profile: wsl
    show_tokens:
      light: l_standup_left_0_4
  sh_wsl_1:
    profile: wsl
    show_tokens:
      light: l_standup_left_1_4
  sh_wsl_2:
    profile: wsl
    show_tokens:
      light: l_standup_left_2_4
  sh_wsl_3:
    profile: wsl
    show_tokens:
      light: l_standup_left_3_4
  sh_wsl_4:
    profile: wsl
    show_tokens:
      light: l_standup_left_4_4
  sh_wsl_5:
    profile: wsl
    show_tokens:
      light: l_standup_left_5_4
  sh_wsl_6:
    profile: wsl
    show_tokens:
      light: l_standup_left_6_4

event_player:
  sh_wide_shot_hit{device.shots.sh_wide_shot.enabled}:  wide_shot_qualified
  mode_wide_shot_started{current_player.wide_shot_progress==1}: wide_shot_init_disable
  mode_wide_shot_started{current_player.wide_shot_progress==0}: wide_shot_init_enable
  wide_shot_qualified: wide_shot_advance_progress
  # sh_wide_shot_hit{device.shots.sh_wide_shot.state_name=='on' and current_player.wide_shot_progress < 2}: wide_shot_advance_progress
  
