#config_version=5

mode:
  start_events: ball_starting
  code: wide_shot.WideShot
  priority: 200

shows:
  off_stop:
    - duration: -1
      lights:
        (light): stop
  flash_stop:
    - time: 0
      lights:
        (light): on
    - time: 1
      lights:
        (light): stop
  wsl_on:
    - duration: -1
      lights:
        (light): on
        (vpx_light): on
    
shot_profiles:
  wsl:
    states:
      - name: off
        show: off_stop
      - name: flash
        show: flash_stop
        speed: 6
      - name: on
        show: wsl_on
  wide_shot:
    advance_on_hit: False
    states:
      - name: flash
        show: flash_stop
      - name: on
        show: on

shots:
  sh_wide_shot:
    switch: s_target_right_0
    advance_events: wide_shot_qualified, wide_shot_collected
    profile: wide_shot
  # 'shots' for lights on grid
  sh_wsl_0:
    profile: wsl
    show_tokens:
      light: l_target_left_0_3
      vpx_light: l_wide_shot_vpx_0
  sh_wsl_1:
    profile: wsl
    show_tokens:
      light: l_target_left_1_3
      vpx_light: l_wide_shot_vpx_1
  sh_wsl_2:
    profile: wsl
    show_tokens:
      light: l_target_left_2_3
      vpx_light: l_wide_shot_vpx_2
  sh_wsl_3:
    profile: wsl
    show_tokens:
      light: l_target_left_3_3
      vpx_light: l_wide_shot_vpx_3
  sh_wsl_4:
    profile: wsl
    show_tokens:
      light: l_target_left_4_3
      vpx_light: l_wide_shot_vpx_4
  sh_wsl_5:
    profile: wsl
    show_tokens:
      light: l_target_left_5_3
      vpx_light: l_wide_shot_vpx_5
  sh_wsl_6:
    profile: wsl
    show_tokens:
      light: l_target_left_6_3
      vpx_light: l_wide_shot_vpx_6

event_player:
  sh_wide_shot_hit{device.shots.sh_wide_shot.state_name=='flash'}:  wide_shot_qualified
  wide_shot_qualified: wide_shot_advance_progress
  # sh_wide_shot_hit{device.shots.sh_wide_shot.state_name=='on' and current_player.wide_shot_progress < 2}: wide_shot_advance_progress

