#config_version=5

# award_4 - tbd

mode:
  start_events: ball_starting

shows:
  spinner_qualified_from_award:
    - duration: 3.5
      segment_displays:
        row_0:
          color: white
          text: "  SUPER SPINNER "
          transition:
            type: push
            direction: left
        row_1:
          color: white
          text: "     ONLINE     "
          transition:
            type: push
            direction: right

# TODO: add test so that show won't play twice if scratch guards are already activated
show_player:
  award_4_collected:
    spinner_qualified_from_award:
      loops: 0
      speed: 1.5
      priority: 100

event_player:
  award_4_collected: spinner_qualified_from_award
