#config_version=5

# award_4 - tbd
mode:
  start_events: award_4_selected
  stop_events: award_4_unselected

shows:
  spinner_qualified_from_award:
    - duration: 2.5
      segment_displays:
        row_0:
          color: white
          text: "  SUPER SPINNER "
          transition:
            type: push
            direction: left
        row_1:
          color: white
          text: "     ONLINE     "
          transition:
            type: push
            direction: right

# TODO: add test so that show won't play twice if scratch guards are already activated
show_player:
  saucer_collect_award_show_start:
    spinner_qualified_from_award:
      loops: 0
      speed: 1.5
      priority: 100
      events_when_completed: award_x_show_complete

event_player:
  saucer_collect_award_show_start:
    - spinner_qualified_from_award
