#config_version=5

mode:
  start_events: ball_starting

shots:
  sh_lane_upper_0:
    hit_events: s_lane_upper_0_active
    show_tokens:
      light: l0
  sh_lane_upper_1:
    hit_events: s_lane_upper_1_active
    show_tokens:
      light: l1
  sh_lane_upper_2:
    hit_events: s_lane_upper_2_active
    show_tokens:
      light: l2
  sh_outlane_left:
    switch: s_outlane_left
    show_tokens:
      light: l_outlane_left_0
  sh_inlane_left:
    switch: s_inlane_left
    show_tokens:
      light: l_inlane_left_0
  sh_inlane_right:
    switch: s_inlane_right
    show_tokens:
      light: l_inlane_right_0
  sh_outlane_right:
    switch: s_outlane_right
    show_tokens:
      light: l_outlane_right_0
