#config_version=5

# TODO: Scratch guards can be lost currently during multiball, they hsould not be enabled if mball is running

mode:
  start_events: ball_starting
  stop_events: scratch_guards_stop

shot_profiles:
  scratch_guards:
    states:
      - name: on
        show: led_color
        show_tokens:
          color: blue

shots:
  sh_scratch_guards_left:
    switch: s_outlane_left
    profile: scratch_guards
    enable_events: scratch_guards_start
    disable_events: sh_scratch_guards_left_hit
    show_tokens:
      light: l_outlane_left
  sh_scratch_guards_right:
    switch: s_outlane_right
    profile: scratch_guards
    enable_events: scratch_guards_start
    disable_events: sh_scratch_guards_right_hit
    show_tokens:
      light: l_outlane_right

ball_saves:
  scratch_guards_left:
    auto_launch: True
    balls_to_save: 1
    enable_events: sh_scratch_guards_left_hit
    disable_events: ball_save_scratch_guards_left_saving_ball
    early_ball_save_events: timer_scratch_guards_left_enabled_delay_complete
  scratch_guards_right:
    auto_launch: True
    balls_to_save: 1
    enable_events: sh_scratch_guards_right_hit
    disable_events: ball_save_scratch_guards_right_saving_ball
    early_ball_save_events: timer_scratch_guards_right_enabled_delay_complete

# need a small delay so early ball save events work correctly
timers:
  scratch_guards_right_enabled_delay:
    end_value: 1
    tick_interval: 100ms
    control_events:
      - action: start
        event: ball_save_scratch_guards_right_enabled
      - action: stop
        event: timer_scratch_guards_right_enabled_delay_complete
      - action: reset
        event: timer_scratch_guards_right_enabled_delay_complete
  scratch_guards_left_enabled_delay:
    end_value: 1
    tick_interval: 100ms
    control_events:
      - action: start
        event: ball_save_scratch_guards_left_enabled
      - action: stop
        event: timer_scratch_guards_left_enabled_delay_complete
      - action: reset
        event: timer_scratch_guards_left_enabled_delay_complete

event_player:
  # TODO: test the case where both of these are hit at the same time, potential race condition
  ball_save_scratch_guards_right_saving_ball{not device.shots.sh_scratch_guards_left.enabled}: scratch_guards_stop
  ball_save_scratch_guards_left_saving_ball{not device.shots.sh_scratch_guards_right.enabled}: scratch_guards_stop
