#config_version=5

mode:
  start_events: ball_starting
  code: mball.Mball

# state_machines:
#   mball:
#     states:
#       start: {}
#       qualifying: {}
#       locked: {}
#       active: {}
#     transitions:
#       # start
#       - source: start
#         target: qualifying
#         events: 
#       - source: start
#         target: locked
#         events: 
#       # qualifying
#       - source: qualifying
#         target: locked
#         events: 
#       # locked
#       - source: locked
#         target: active
#         events: 
#       # active

multiballs:
  main:
    ball_count: 2
    ball_count_type: total
    shoot_again: 11s
    ball_locks: bd_scoop_upper
    start_events: mball_main_start

multiball_locks:
  scoop_upper:
    balls_to_lock: 1
    lock_devices: bd_scoop_upper
    locked_ball_counting_strategy: physical_only
    # reset_count_for_current_player_events: multiball_main_started



    
