#config_version=5

mode:
  start_events: start_mball
  stop_events: start_mball_qualifying

event_player:
  timer_mball_eject_delay_complete:
    - activate_smart_drop_upper
  multiball_main_ended: start_mball_qualifying

timers:
  mball_eject_delay:
    start_running: True
    end_value: 3
