#config_version=5

# award_2 - TBD

mode:
  start_events: award_2_selected
  stop_events: award_0_selected, award_1_selected, award_3_selected, award_4_selected, award_5_selected, award_6_selected

event_player:
  award_2_collected: scratch_guards_start



